# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-ai-labbet-test01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fd1e3467e25c45c785d42d2c31243565 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b147d102c3bd4ad1b3aa1abb98359989 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fd1e3467e25c45c785d42d2c31243565 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-ai-labbet-test01'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_97b85fb203544d289f28e110ecbc07b8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fd1e3467e25c45c785d42d2c31243565 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'